# Generated by Django 4.1.1 on 2022-09-28 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(blank=True, max_length=30, null=True)),
                ('SPZ', models.CharField(blank=True, max_length=7, null=True)),
                ('car_type', models.CharField(blank=True, choices=[('PERSONAL', 'PERSONAL'), ('TRUCK', 'TRUCK')], max_length=20, null=True)),
            ],
        ),
    ]
