# Generated by Django 4.1.1 on 2022-09-28 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formular_web', '0002_mycontact_delete_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycontact',
            name='contact_group',
            field=models.CharField(blank=True, choices=[('PRE-SALES', 'PRE-SALES'), ('SALESS', 'SALESS'), ('SERVICE', 'SERVICE')], max_length=50, null=True),
        ),
    ]
