# Generated by Django 4.1.1 on 2022-09-29 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formular_web', '0004_mycontact1'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('second_name', models.CharField(blank=True, max_length=50, null=True)),
                ('ID_number', models.CharField(blank=True, max_length=8, null=True)),
                ('email', models.EmailField(blank=True, max_length=30, null=True)),
                ('car_brand', models.CharField(blank=True, max_length=30, null=True)),
                ('car_type', models.CharField(blank=True, choices=[('TRUCK', 'TRUCK'), ('PERSONAL', 'PERSONAL'), ('BUS', 'BUS'), ('CYCLE', 'CYCLE')], max_length=30, null=True)),
                ('spz', models.CharField(blank=True, max_length=7, null=True)),
                ('registration_date', models.DateField()),
                ('vin', models.FloatField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='MyContact',
        ),
        migrations.DeleteModel(
            name='MyContact1',
        ),
    ]
